set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Vi mode
setw -g mode-keys vi
bind-key -T copy-mode-vi 'j' send-keys -X scroll-down
bind-key -T copy-mode-vi 'k' send-keys -X scroll-up
bind-key -T copy-mode-vi 'C-d' send-keys -X halfpage-down
bind-key -T copy-mode-vi 'C-u' send-keys -X halfpage-up
